name: Publish to Packagist
run-name: "${{ github.repository }} -> Packagist by ${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish-packagist:
    runs-on: [self-hosted, graffino, php8.3]

    environment: Production
    env:
      PACKAGE_NAME: graffino/n8n-eloquent
      PACKAGIST_URL: https://packagist.org/api/
      COMPOSER_AUTH: '{"http-basic": {"repo.packagist.com": {"username": "${{ secrets.PACKAGIST_USERNAME }}", "password": "${{ secrets.PACKAGIST_TOKEN }}"}}}'

    permissions:
      contents: read
      packages: write
      id-token: write
      actions: write

    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: success()

      - name: Get version
        id: Get-Version
        run: |
          VERSION_TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v2.1.0")
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          VERSION_NO=${VERSION_TAG#v}
          echo "VERSION_NO=$VERSION_NO" >> $GITHUB_ENV
          echo "version=$VERSION_NO" >> $GITHUB_OUTPUT
          
      - name: Sync versions
        run: |
          chmod +x scripts/sync-versions.sh
          ./scripts/sync-versions.sh ${{ steps.Get-Version.outputs.version }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, zip
          coverage: none

      - name: Install Composer
        uses: ramsey/composer-install@v2
        with:
          composer-version: '2.6'
          dependency-versions: 'locked'
          install-preferred-packages: true

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader

      - name: Run tests
        run: |
          composer install --prefer-dist --dev
          vendor/bin/phpunit --coverage-text --coverage-filter=src/

      - name: Create package archive
        run: |
          composer archive --format=zip --dir=dist/ --file="${{ env.PACKAGE_NAME }}-${{ steps.Get-Version.outputs.version }}.zip"

      - name: Verify package structure
        run: |
          ls -la dist/
          unzip -l "dist/${{ env.PACKAGE_NAME }}-${{ steps.Get-Version.outputs.version }}.zip" | head -20

      - name: Update composer.json version
        run: |
          composer config version ${{ steps.Get-Version.outputs.version }}

      - name: Publish to Packagist
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}' \
            "${{ env.PACKAGIST_URL }}update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"

      - name: Wait for Packagist update
        run: |
          echo "Waiting for Packagist to update..."
          sleep 30

      - name: Verify Packagist publication
        run: |
          curl -s "https://packagist.org/packages/${{ env.PACKAGE_NAME }}.json" | jq '.package.versions | keys | .[-1]'

      - name: Create release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
            composer.json
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
